# This config file has all the autocorrectable rules disabled. This makes it easy to 
# run autocorrect for a specific ruleset
#
# You can use this file by commenting out the rule you would like to be enabled
# then run 'swiftlint autocorrect --config .swiftlint.auto.yml' from your command line
# disabled_rules:
# - anyobject_protocol
# - closing_brace
# - closure_end_indentation
# - closure_spacing
# - colon
# - comma
# - control_statement
# - empty_enum_arguments
# - empty_parameters
# - empty_parentheses_with_trailing_closure
# - explicit_init
# - explicit_self
# - implicit_return
# - joined_default_parameter
# - leading_whitespace
# - legacy_cggeometry_functions
# - legacy_constant
# - legacy_constructor
# - legacy_nsgeometry_functions
# - literal_expression_end_indentation
# - mark
# - modifier_order
# - nimble_operator
# - no_space_in_method_call
# - number_separator
# - opening_brace
# - operator_usage_whitespace
# - optional_enum_case_matching
# - prefer_self_type_over_type_of_self
# - private_over_fileprivate
# - protocol_property_accessors_order
# - redundant_discardable_let
# - redundant_nil_coalescing
# - redundant_objc_attribute
# - redundant_optional_initialization
# - redundant_type_annotation
# - redundant_void_return
# - return_arrow_whitespace
# - sorted_imports
# - statement_position
# - syntactic_sugar
# - toggle_bool
# - trailing_comma
# - trailing_newline
# - trailing_semicolon
# - trailing_whitespace
# - unneeded_parentheses_in_closure_argument
# - untyped_error_in_catch
# - unused_closure_parameter
# - unused_control_flow_label
# - unused_import
# - vertical_whitespace
# - vertical_whitespace_between_cases
# - vertical_whitespace_closing_braces
# - vertical_whitespace_opening_braces
# - void_return
# - weak_delegate
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
reporter: "emoji"
